### ISSUE TITLE
TypeError: programPath.hub.addHelper is not a function

### ISSUE THREAD

**Issue by Saif-Uz-Zaman** [storybooks/vue-cli-plugin-storybook#29] opened 2018-09-18 13:13 UTC
### vue add storybook failed to run

`WARNING in ./src/stories/index.stories.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: programPath.hub.addHelper is not a function
    at wrapInterop (C:\Users\saifm\development\practice\storybook-vue\node_modules\@storybook\core\node_modules\@babel\helper-module-transforms\lib\index.js:165:45)
    at PluginPass.exit (C:\Users\saifm\development\practice\storybook-vue\node_modules\@storybook\core\node_modules\@babel\plugin-transform-modules-commonjs\lib\index.js:174:70)
    at newFn (C:\Users\saifm\development\practice\storybook-vue\node_modules\@babel\traverse\lib\visitors.js:237:21)
    at NodePath._call (C:\Users\saifm\development\practice\storybook-vue\node_modules\@babel\traverse\lib\path\context.js:65:20)
    at NodePath.call (C:\Users\saifm\development\practice\storybook-vue\node_modules\@babel\traverse\lib\path\context.js:40:17)
    at NodePath.visit (C:\Users\saifm\development\practice\storybook-vue\node_modules\@babel\traverse\lib\path\context.js:109:8)
    at TraversalContext.visitQueue (C:\Users\saifm\development\practice\storybook-vue\node_modules\@babel\traverse\lib\context.js:142:16)
    at TraversalContext.visitSingle (C:\Users\saifm\development\practice\storybook-vue\node_modules\@babel\traverse\lib\context.js:102:19)
    at TraversalContext.visit (C:\Users\saifm\development\practice\storybook-vue\node_modules\@babel\traverse\lib\context.js:182:19)
    at Function.traverse.node (C:\Users\saifm\development\practice\storybook-vue\node_modules\@babel\traverse\lib\index.js:106:17)
    at traverse (C:\Users\saifm\development\practice\storybook-vue\node_modules\@babel\traverse\lib\index.js:76:12)
    at transformFile (C:\Users\saifm\development\practice\storybook-vue\node_modules\@babel\core\lib\transformation\index.js:116:29)
    at runSync (C:\Users\saifm\development\practice\storybook-vue\node_modules\@babel\core\lib\transformation\index.js:45:3)
    at runAsync (C:\Users\saifm\development\practice\storybook-vue\node_modules\@babel\core\lib\transformation\index.js:35:14)
    at process.nextTick (C:\Users\saifm\development\practice\storybook-vue\node_modules\@babel\core\lib\transform.js:34:34)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
 @ ./src/stories sync .stories.js$ ./index.stories.js
 @ ./config/storybook/config.js
 @ multi ./node_modules/@storybook/core/dist/server/config/polyfills.js ./node_modules/@storybook/core/dist/server/config/globals.js ./config/storybook/config.js (webpack)-hot-middleware/client.js?reload=true
i ｢wdm｣: Compiled with warnings.`

plz help

**Comment by pksunkara** [comment] 2018-09-18 13:45
Duplicate of #22

**Closed by pksunkara** 2018-09-18 13:45 UTC
