### ISSUE TITLE
Can't get default example to run

### ISSUE THREAD

**Issue by DanielPe05** [storybooks/vue-cli-plugin-storybook#25] opened 2018-09-13 18:31 UTC
This is a new vue-cli fresh install:
```
"devDependencies": {
    "@storybook/addon-actions": "^4.0.0-alpha.20",
    "@storybook/addon-links": "^4.0.0-alpha.20",
    "@vue/cli-plugin-babel": "^3.0.1",
    "@vue/cli-plugin-eslint": "^3.0.1",
    "@vue/cli-plugin-unit-jest": "^3.0.1",
    "@vue/cli-service": "^3.0.1",
    "@vue/eslint-config-prettier": "^3.0.3",
    "@vue/test-utils": "^1.0.0-beta.25",
    "babel-core": "7.0.0-bridge.0",
    "babel-jest": "^23.6.0",
    "lint-staged": "^7.2.2",
    "node-sass": "^4.9.0",
    "sass-loader": "^7.0.1",
    "vue-cli-plugin-storybook": "^0.4.7",
    "vue-cli-plugin-styleguidist": "^0.1.3",
    "vue-template-compiler": "^2.5.17"
  },
```

However the default example right after the plugin is installed fails with this:
```
WARNING in ./src/stories/index.stories.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: /Users/xxxx/Personal/skunkworks/src/stories/index.stories.js: Duplicate declaration "h" (This is an error on an internal node. Probably an internal error.)
```

When I remove the story that uses JSX I get the following error:
```
WARNING in ./src/stories/index.stories.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: programPath.hub.addHelper is not a function
```

Any idea what could be causing is?

**Comment by dbalas** [comment] 2018-09-13 18:44
Duplicate of #22

**Closed** 2018-09-13 19:40 UTC
Labels: duplicate
